### ISSUE TITLE
Neden devam edilmedi?

### ISSUE THREAD

**Issue by cartals** [Sevenops/TurkAnime-Downloader#1]
Neden devam edilmedi ya tam da bana lazım bir şey :D

**Comment by Sevenops** [comment]
O zamanlar kendi ihtiyaçlarım için yazmıştım sonrasında torrent kullanmaya başladığım için gerek duymadım. Eğer bu tarz şeyler ile ilgileniyorsan Manga Tube/Manga Oku uygulamasının sunucu tarafını githubda paylaşabilirim manga indirmek için kullanabilirsin onu.

**Comment by cartals** [comment]
Manga pek ilgilenmiyorum, keşke türkanime olarak devamı olsa bizim gibi kullanıcılara işe yarardı neyse, geri dönüşün için çok teşekkürler!

**Comment by gokaybiz** [comment]
Artık vk neredeyse kullanılmıyor. Değişik değişik alternatifler türedi. Downloader yazılması pek mümkün değil. Hemen her alternatif için koşul yazılmalı ve stabil çalışacağının hiçbir garantisi yok.

**Comment by KebabLord** [comment]
> Artık vk neredeyse kullanılmıyor. Değişik değişik alternatifler türedi. Downloader yazılması pek mümkün değil. Hemen her alternatif için koşul yazılmalı ve stabil çalışacağının hiçbir garantisi yok.
vk hakikaten ölü ancak alternatif çeşitliliği seni yanıltmasın. Youtube-dl + mpv + ffmpeg'in zengin kütüphanesi ile tam anlamıyla herşeyi oynatabiliyorsun. Şuan bende bi downloader üstünde çalışıyorum, umarım başarılı olur. Şuanlık türkanime,fembed,rapidshare çalışıyor

**Comment by KebabLord** [comment]
> Artık vk neredeyse kullanılmıyor. Değişik değişik alternatifler türedi. Downloader yazılması pek mümkün değil. Hemen her alternatif için koşul yazılmalı ve stabil çalışacağının hiçbir garantisi yok.

vk hakikaten ölü ancak alternatif çeşitliliği seni yanıltmasın. Youtube-dl + mpv + ffmpeg'in zengin kütüphanesi ile tam anlamıyla herşeyi oynatabiliyorsun. Şuan bende bi downloader üstünde çalışıyorum, umarım başarılı olur. Şuanlık türkanime,fembed,rapidshare çalışıyor

**Comment by cartals** [comment]
@KebabLord yayınlasanda yararlansak :D ne zaman çıkarırsın tahmini?

**Comment by KebabLord** [comment]
yakın zamanda olacağını pek sanmıyorum dost ;_;
Tam özellikli olmasını ve mpv'nin bütün nimetlerinden faydalanabilmesini hedefliyorum. Animeyi izlerken bilgisayarina kaydetmesi özelliği gibi.
SevenOpsun yazdiği bu versiyon türkanime tasarimini yenileyince  geçerliliğini kaybetti. Şimdi tarayıcı otomasyonuyla boğuşuyorum fansub seçiyor, alternatifleri belirliyor vb.

@Sevenops sayfayı direk fansub seçilmiş bir şekilde yüklemenin bir yolu var mıdır dersin. Önceden php get talebi gonderiyordu url'den okunuyordu. Sanırım gizlediler ;_;

**Comment by gokaybiz** [comment]
Bolum listesinden, kategori listesine, bolum ici alternatiflerden embedlere/raw linklere varana kadar duzenli bir sekilde getiren bir sey yazmistim 1 ay kadar once.
Yazdigim api'i servis edebilirim projen icin.
youtube-dl'in sadece youtube servisi icin calistigini saniyorum. :pager:

**Comment by KebabLord** [comment]
Woah, bir fansubu ve video alternatiflerini selenyum kullanmadan nasıl seçer video konumuna ulaşırım bir türlü bulamamıştım. 
Aslında bi yönlendirici url'sine ulaştım ama bi işe yaramadı.
Api'n bunu sağlayabilirse bu herşeyi kolaylaştırır. Video urlsine ulaştıktan sonrası kolay demek istiyorum yani. Urllib, requests, selenium hangisini veya hangi dili kullandın dost?

**Comment by Sevenops** [comment]
gençler aslında bu tarz bir projeye devam da edilebilir ancak direkt torrent + altyazı için bir sistem yazmak daha mantıklı ve artık çoğu torrent kütüphanesi indirirken izlemeyi mümkün kılıyor.

**Comment by gokaybiz** [comment]
Ben Javascript ile yazdım.
Kullandığım kütüphanelerinin muadillerini Python için arayacak olursak Requests ve PyQuery kullandım diyebiliriz.
Ama zahmet etme istersen, kullanılabilir hale getirip heroku'ya deploy edeyim.

**Comment by Sevenops** [comment]
Turkcealtyazı ve planetdp gibş yerlere altyazı hemen düşüyor en erken ise torrentlere horriblesubs ve birçok sub zaten torrent linki veriyor. Son zamanlarda webtorrent teknolojisi de gelişti kullananı nispeten daha az ancak masaüstü ve mobil için torrent uygun

**Comment by cartals** [comment]
@Sevenops bence tam tersi çeviriler çok geç geliyor hele ki yeni sezon animelerinde işkence resmen o yüzden ingilizce öğrenmeye başladım :smile:

**Comment by KebabLord** [comment]
en popüler ingilizce alternatifleri destekleyen bi anime downloader/player reposu [zaten mevcut](https://github.com/vn-ki/anime-downloader).
Our aim is to create one for türkanime!  :-3

**Comment by Sevenops** [comment]
Olur düzgün bir api oluşturmaya başlayalım o zaman. Türkanimede 1080p olmadığı için ben torrent demiştim.

**Comment by KebabLord** [comment]
mpv+ffmpeg+youtube-dl ile video indirebildiğim ve uzaktan oynatabildiğim alternatifler; mailru, ok.ru, myvi, türkanime,hdvid,  openload, fembed (ufak bi trick ile), rapid, streamango & streamcherry, rutube.

Video url'lerine seleniumsuz ulaşmak mümkün ise hojem, videolar cepte :3

**Comment by gokaybiz** [comment]
Anlik iletisim kurabilecegimiz bir platforma gecelim.

**Comment by cartals** [comment]
Benim yazılımla pek alakam yok ama anlık iletişime geçebileceğiniz platformda takip etmek isterim :D

**Comment by KebabLord** [comment]
neden olmasın :333
şahsen irc kullanıyorum ancak dickscord hesabum da mevcuttur, Juko#1558

**Comment by Sevenops** [comment]
Telegram da olabilir kanal açtım gelirseniz burdan devam ederiz ya da discorda açarız

https://t.me/joinchat/AAAAAFjTuaR3YOxalKRq0w

**Comment by KebabLord** [comment]
telegram kullanmak için bahane arıyordum, geliyorum üstard

**Comment by cartals** [comment]
discord olsa güzel olurdu elinize sağlık şimdiden

**Comment by Sevenops** [comment]
Dc de açtım hangisinde daha rahat edersek orayı kalıcı olarak seçeriz

https://discord.gg/kVZwJrn

**Comment by Sevenops** [comment]
Projeye https://discord.gg/kVZwJrn adresinde tartışarak devam ediyoruz şimdilik kapatıyorum.
